spring:
  application:
    name: Shipping-Service
  datasource:
    url: jdbc:h2:mem:shippingdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    # Disable hibernate auto schema creation
    hibernate:
      ddl-auto: none
  h2:
    console.enabled: true
  # Makes console log output colourful
  output:
    ansi:
      enabled: ALWAYS
  lifecycle:
    timeout-per-shutdown-phase: 20s
  kafka:
    consumer:
      group-id: orders-group
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        "[spring.json.trusted.packages]": "com.shop.generic.common.kmos"
      auto-offset-reset: latest
    bootstrap-servers: "localhost:9092"
  threads:
    virtual:
      enabled: true
#  main:
#    web-application-type: none

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      group:
        liveness:
          include:
            - livenessState
            - db
            - ping
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
server:
  port: 8084
  servlet:
    context-path: "/shipping-service"
  shutdown: graceful

services:
  order-service:
    url: http://localhost:8083/order-service

gsshop-common:
  auth:
    enabled: true
    jwt-token-secret: c63714bee7677d179d980aeceffb1a2ac63ebb25933cc16ad58d90f043b9da9f1c22b6d70e7ec8183884108eb6660be5d1cfba7da55b56cfa6e8ba201f97370a
    jwt-token-salt: abcd1234
    jwt-token-validity: 3600000

# Logs to file and allows SBA to pick it up as well
logging:
  file:
    name: logs/shipping-service.log

scheduler:
  tasks:
    pending-status-update: 1 #in minutes
    inprogress-status-update: 1 #in minutes

topics:
  order: orders
